fastlane_version "2.28.3"

default_platform :ios

platform :ios do
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "WikiRaces") # Build your app - more options available
    changelog_from_git_commits(pretty:"[%ad] %s", date_format:"short")
    upload_to_testflight(distribute_external:true, notify_external_testers:false, groups: ["External Testers"])
  end
end

