# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
 devices([
"iPad Pro",
 ])

languages([
  "en-US"
])

scheme "WikiRacesScreenshots"

dark_mode false

clear_previous_screenshots false

project "./WikiRaces.xcodeproj"

