# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
 devices([
"iPad Pro (12.9-inch) (4th generation)",
"iPhone 11 Pro Max",
"iPhone 8 Plus",
 ])

languages([
"en-US",
 "nl-NL",
"fr-FR",
"de-DE",
"ja",
"ru",
"es-ES",
])

scheme "WikiRacesScreenshots"

override_status_bar true 

dark_mode true

clear_previous_screenshots false

project "./WikiRaces.xcodeproj"

